### ISSUE TITLE
{'result': None, 'success': False, 'message': 'INVALID_SIGNATURE'}

### ISSUE THREAD

**Issue by karthikdhanusu** [ericsomdahl/python-bittrex#136]
I made the following changes in bittrex code still I am getting invalid signature error

request_url += urllib.parse.urlencode(options)
signature = hmac.new(self.api_secret.encode('utf-8'), request_url.encode('utf-8'), hashlib.sha512).hexdigest()

can someone help me ?

**Comment by karthikdhanusu** [comment]
It works with python 2.7 not on python 3

**Comment by FullKickProductions** [comment]
I'm also running into this error!

**Comment by FullKickProductions** [comment]
Is there no workaround? I have to stick with python 3 to support some of the other libraries I'm using! Any help will be hugely appreciated.

**Comment by cryptobeaver** [comment]
You can run Python 2.7 and 3 in separate install folders (i'm on mac) and then when running python 2.7 you just call it with python2.7 if my memory serves me right.

**Comment by FullKickProductions** [comment]
Thanks for the response @cryptobeaver, The trouble is that my application has to use python 3.6 in order to support some of the other libraries. I don't want to drop support for any of them, but I would like to support bittrex trading. Unless I can call the bittrex methods from python 3.6, I'm going to have to find another exchange to work with :(

**Comment by hpr0009** [comment]
Bump again

**Comment by forgetso** [comment]
I have fixed this in a fork: https://github.com/forgetso/python-bittrex/commit/6d0cb933e47a64a4972f621695b3362e66ec191a

**Comment by g0tzz** [comment]
> I have fixed this in a fork: [forgetso@6d0cb93](https://github.com/forgetso/python-bittrex/commit/6d0cb933e47a64a4972f621695b3362e66ec191a)

I'm still getting this error even with your fix. Anyone still having this issue? Or are you using V1.1?
